### ISSUE TITLE
Fix bluetooth discovery

### ISSUE THREAD

**Issue by barakcohen** [barakcohen/whatsnearme#1]
At the moment Bluetooth devices (both legacy and BLE) are not discovered correctly.

**Comment by silvamb** [comment]
Bluetooth discovery logic has been reformulated. Now, once the "classic" devices are discovered, the Low Energy devices are scanned, for 10 seconds. After this scan is done, the discovery starts again, after a 1 second delay.

**Comment by barakcohen** [comment]
Great. Let me know when u have a new drop

Sent by Outlook for Android

On Thu, Nov 5, 2015 at 9:18 AM -0800, "Matheus Barbosa e Silva" notifications@github.com wrote:
Bluetooth discovery logic has been reformulated. Now, once the "classic" devices are discovered, the Low Energy devices are scanned, for 10 seconds. After this scan is done, the discovery starts again, after a 1 second delay.

---

**Comment by barakcohen** [comment]
App still does not recognize the car Bluetooth audio systems. I will test with more devices on Friday

**Comment by silvamb** [comment]
There was a small bug, that prevented any LE devices detected to be listed. I hope that bug was the cause for the car audio system are not recognized.The fix is available in the version 1.0.0-RC03. I will send you the link
