### ISSUE TITLE
Add an app icon

### ISSUE THREAD

**Issue by barakcohen** [barakcohen/whatsnearme#3]
App needs an icon. You can use these files (if you need other formats, let me know) : 
![whatsnearme32](https://cloud.githubusercontent.com/assets/8920515/10991305/07444340-8411-11e5-9702-cacb84f4b71e.png)
![whatsnearme48](https://cloud.githubusercontent.com/assets/8920515/10991308/0745e362-8411-11e5-8659-199178c5dc89.png)
![whatsnearme64](https://cloud.githubusercontent.com/assets/8920515/10991307/0745df02-8411-11e5-8ef6-0829af528f9a.png)
![whatsnearme128](https://cloud.githubusercontent.com/assets/8920515/10991306/0745a9a6-8411-11e5-9523-82964ff2ec42.png)
![whatsnearme256](https://cloud.githubusercontent.com/assets/8920515/10991309/0745ec86-8411-11e5-8199-09374e95ee29.png)

**Comment by silvamb** [comment]
Icon is being used for app icon and notifications. Available in version 1.0.0-RC03
