### ISSUE TITLE
The same bluetooth device is registering twice

### ISSUE THREAD

**Issue by barakcohen** [barakcohen/whatsnearme#4]
Although not every device is registering some devices are registering twice
![screenshot_2015-11-05-15-41-29](https://cloud.githubusercontent.com/assets/8920515/10991357/6cc4d61c-8411-11e5-9000-877a09393985.png)

**Comment by silvamb** [comment]
Changed the code to verify if a device is already added to the devices list. Available in the version 1.0.0-RC03
