### ISSUE TITLE
Device to device between Samsung S5 and Motorola G does not work

### ISSUE THREAD

**Issue by barakcohen** [barakcohen/whatsnearme#6]
I installed the app on both devices and tried to recognize the phone running the app, does not work on both sides (you maybe testing on two KitKat devices)

**Comment by silvamb** [comment]
The phone recognition algorithm has been entirely remade. Now the user must register the mac address of a known device that runs the app. When the app discover a device nearby with a registered mac address, it points the device in the "Phones that run the app area"
