### ISSUE TITLE
app notification icon is corrupt (shows as blank) on lillipop, ok on kitkat

### ISSUE THREAD

**Issue by barakcohen** [barakcohen/whatsnearme#7]
Some other lollipop behavior, the app icon is corrupt (shows as a blank circle). You may need to provide a different bitmap

**Comment by silvamb** [comment]
Lollipop is a little more restrictive with icons.
For the notifications bar, I need the icon with no background and with white lines. This is the pattern recommended: https://www.google.com/design/spec/patterns/notifications.html#notifications-guidelines

For the notification icon, the icons must be resized for a 24dp resolution: 24x24, 36x36, 48x48, 72x72, 96x96.

**Comment by barakcohen** [comment]
OK, I will provide you with some

Sent by Outlook for Android

On Sun, Nov 8, 2015 at 11:33 AM -0800, "Matheus Barbosa e Silva" notifications@github.com wrote:
Lollipop is a little more restrictive with icons.
For the notifications bar, I need the icon with no background and with white lines. This is the pattern recommended: https://www.google.com/design/spec/patterns/notifications.html#notifications-guidelines

For the notification icon, the icons must be resized for a 24dp resolution: 24x24, 36x36, 48x48, 72x72, 96x96.

---

**Comment by barakcohen** [comment]
Attached are updated icons that will work on Lollipop (and marshmallow)
![whatsnearme24](https://cloud.githubusercontent.com/assets/8920515/11128403/603a11a6-892e-11e5-9039-50197e0f6fbb.png)
![whatsnearme36](https://cloud.githubusercontent.com/assets/8920515/11128402/603a0530-892e-11e5-909c-d36b0d9b8ed3.png)
![whatsnearme48](https://cloud.githubusercontent.com/assets/8920515/11128404/603c2ad6-892e-11e5-9e9a-58bbcee60ea1.png)
![whatsnearme72](https://cloud.githubusercontent.com/assets/8920515/11128401/60396652-892e-11e5-9c57-633f93a64965.png)
![whatsnearme96](https://cloud.githubusercontent.com/assets/8920515/11128405/603e8498-892e-11e5-823f-814157a73c92.png)
