### ISSUE TITLE
Update spec: add setting to have a signal strength threshold for WIFI

### ISSUE THREAD

**Issue by barakcohen** [barakcohen/whatsnearme#8]
With adding threshold setting for WiFi, the app will record more local access point than remote ones. That will help the use track what is near.

**Comment by silvamb** [comment]
I understand this threshold will limit the discovered networks, considering the signal strength in dBm. Ok?

**Comment by barakcohen** [comment]
Yes

Sent by Outlook for Android

On Sun, Nov 8, 2015 at 10:55 AM -0800, "Matheus Barbosa e Silva" notifications@github.com wrote:
I understand this threshold will limit the discovered networks, considering the signal strength in dBm. Ok?

---

**Comment by silvamb** [comment]
Feature available in version 1.0.0-RC10. The user can set the wifi level threshold in the settings menu option. The minimum default value is -90 dBm
